# ---------- BASE ----------
FROM node:20-alpine AS base
WORKDIR /app

# только package.json для кеша зависимостей
COPY core-app/package*.json ./core-app/
COPY user-app/package*.json ./user-app/
COPY dashboard-app/package*.json ./dashboard-app/

# ставим зависимости ОДИН РАЗ НА APP (кешируется слоями)
RUN cd core-app && npm install
RUN cd user-app && npm install
RUN cd dashboard-app && npm install


# ---------- BUILD ----------
FROM base AS builder
WORKDIR /app

# теперь копируем код отдельно (не ломая кеш npm)
COPY ./../core-app ./core-app
COPY ./../user-app ./user-app
COPY ./../dashboard-app ./dashboard-app

RUN cd core-app && npm run build
RUN cd user-app && npm run build
RUN cd dashboard-app && npm run build


# ---------- RUNTIME ----------
FROM nginx:alpine

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/core-app/dist /usr/share/nginx/html/
COPY --from=builder /app/user-app/dist /usr/share/nginx/html/user/
COPY --from=builder /app/dashboard-app/dist /usr/share/nginx/html/dashboard/