events {}

http {
  server {
    listen 80;

    # CORE (host app)
    location / {
      proxy_pass http://core:3000;
      proxy_set_header Host $host;
    }

    # USER MF
    location /user/ {
      proxy_pass http://user:3001/;
      proxy_set_header Host $host;
    }

    # PROFILE MF
    location /profile/ {
      proxy_pass http://profile:3002/;
      proxy_set_header Host $host;
    }
  }
}